# ORM Settings
datasource:
  default: ${APP_ENV}
  development:
    username: sa
    password: sa
    url: "jdbc:h2:./app_database"
  production:
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    url: ${JDBC_DATABASE_URL}
    #url: "jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}"

# Run database migrations on startup
ebean:
  migration:
    run: true
